### ISSUE TITLE
Error when installing and when using encrypted volume

### ISSUE THREAD

**Issue by svdo** [linode/linode-blockstorage-csi-driver#158]
Hi! I am looking into switching our deployment to LKE. Currently I'm investigating how to handle storage, specifically also encrypted storage, so I found the linode-blockstorage-csi-driver GitHub repo. I have a question about it, which I posted on the Slack channel as requested in the issue template, but it doesn't look like anybody is reading it over there, so please forgive me for reposting the question here.

When I follow the installation steps in the README over there, I get this error:

```
$ helm upgrade linode-csi-driver --install --set apiToken=$LINODE_API_TOKEN,region=$REGION linode-csi/linode-blockstorage-csi-driver

Release "linode-csi-driver" does not exist. Installing it now.
Error: Unable to continue with install: ServiceAccount "csi-controller-sa" in namespace "kube-system" exists and cannot be imported into the current release: invalid ownership metadata; label validation error: missing key "app.kubernetes.io/managed-by": must be set to "Helm"; annotation validation error: missing key "meta.helm.sh/release-name": must be set to "linode-csi-driver"; annotation validation error: missing key "meta.helm.sh/release-namespace": must be set to "default"
```

I'm not sure how to proceed, is this a bug? Am I doing something wrong? When I ignore it and try to create a deployment with a luks-encrypted volume, I get errors like these:

```
MountVolume.MountDevice failed for volume "pvc-4e9bde95bec9400a" : rpc error: code = Internal desc = Unable to find device path out of attempted paths: [/dev/disk/by-id/linode-pvc4e9bde95bec9400a /dev/disk/by-id/scsi-0Linode_Volume_pvc4e9bde95bec9400a]
  Warning  FailedMount             14s                kubelet                  MountVolume.MountDevice failed for volume "pvc-4e9bde95bec9400a" : rpc error: code = Internal desc = Failed to luks format ("/dev/disk/by-id/scsi-0Linode_Volume_pvc4e9bde95bec9400a"): temporary directory /tmp is not a tmpfs volume; refusing to write luks key to a volume backed by a disk
```

I do see the volume in the Linode Manager web site. Thanks for your help!

**Comment by avestuk** [comment]
@svdo Thanks for opening an issue and apologies for not reacting to slack. I actually didn't know that channel existed but I've joined it now. 

LKE preinstalls the CSI driver so I think that's why you are seeing that issue from helm. 

For the second issue, our current implementation requires that the LUKS key be written to disk in order for it to be passed to cryptsetup. However in order to ensure that you don't leak your keys we will only write the key to a tmpfs volume. 

https://github.com/linode/linode-blockstorage-csi-driver/blob/main/pkg/linode-bs/luks.go#L328-L331

A temporary fix would be to make `/tmp` inside the `csi-linode-node` daemonset an emptyset volume with medium type Memory. I say temporary as your changes will be overwritten every 4h or so as LKE manages the CSI driver deployment. I realise that's not a permanent solution but you can test things that way. 

For a permanent solution, I'll update the daemonset on the LKE side so that `/tmp` is a tmpfs and I can update you here when that is done.

**Comment by svdo** [comment]
That's great Alex, thank you! Once it's deployed I will be sure to try it again.

**Comment by avestuk** [comment]
@svdo Sorry for the delay in responding but this has been released to all versions of LKE now.
