### ISSUE TITLE
Implement Raw Block PVC support

### ISSUE THREAD

**Issue by displague** [linode/linode-blockstorage-csi-driver#25]
Raw Block Volume support has moved to beta.  Since Linode permits raw block volumes, this should simply mean supporting `volumeMode: Block` to bypass the FS formatting.

https://kubernetes.io/blog/2019/03/07/raw-block-volume-support-to-beta/

Implement this according to the docs on https://kubernetes-csi.github.io/docs/raw-block.html (TBD)

Does this require updating the sidecars too -- to what version?

https://github.com/kubernetes/enhancements/blob/master/keps/sig-storage/20190130-csi-raw-block-support.md

Also make a PR to https://kubernetes-csi.github.io/docs/drivers.html to update Linode status.

**Comment by vholer** [comment]
There is only an old stale unmerged PR #31 :-(.
I'm wondering why this hasn't again more attraction in recent 3 years.

**Comment by srust** [comment]
Hi @vholer am curious about your use-case. You're looking to run rook/ceph on top of Linode volumes?

This is probably not the feature you are looking for. Linode volumes (and LKE PVCs) are backed by a highly available storage service already. So you would be trying to layer a replicated storage service on top of an "elastic" storage service. Not going to be a great experience.

What I think you're really asking for is "local volumes" that are high performance that are available to a linode, that then a rook/ceph can consume in order to create a highly available storage service. Local volume support is not something planned for at this time.

Out of curiosity, what are you looking to improve or do by running rook/ceph yourself?

**Comment by stickeepaul** [comment]
Trying not to hijack the thread but thought I'd add our use case:

We've used [ArgoCD](https://argo-cd.readthedocs.io/en/stable/) to build a dynamic staging/UAT _thing_ where Pull Requests from GitHub are deployed using a helm template to a LKE cluster. This is our first step towards moving our apps to "cloud-native" deployments in production.

The one area we had a problem was "local" storage that allowed `ReadWriteMany` for each of the 100ish deployments (apps x PRs) since some of them currently expect a local filesystem for file processing and access to storage is shared between web/app and worker pods.

Using LKE PVC was great but the minimum size is 10GB and most of the apps only need 1GB max - which means we'd be paying 10x what we need. 

It also doesn't (or didn't? it's been a while) support `ReadWriteMany` and [this answer](https://www.linode.com/community/questions/22004/kubernetes-pvcs-with-readwritemany) on the Linode Community Forum and [this Linode guide](https://www.linode.com/docs/guides/how-to-install-rooknfs-on-lke/) suggest installing [`rook/nfs`](https://github.com/rook/nfs) which has support for it. However since they were written rook deprecated `rook/nfs`. It still works but it would have been difficult for me to explain to my CTO that we had built a new forward-facing system using something that was deprecated. 

We tried using `rook/rook` but [it needs a raw block PVC](https://github.com/rook/rook/blob/release-1.10/deploy/examples/cluster-on-pvc.yaml#L134-L137) which led me to this issue.

I can understand why this isn't/won't be prioritised but without `ReadWriteMany` support for LKE PVC we were trying to use `rook/rook` as a workaround and it needs raw block PVC support.

For those curious our working workaround was to attach block storage to a "support" server, make it available through NFS and install [kubernetes-sigs/nfs-subdir-external-provisioner](https://github.com/kubernetes-sigs/nfs-subdir-external-provisioner) to manage the provisioning. This is for a staging environment so performance wasn't a priority. I have to occasionally monitor the block storage usage but we get mostly-hands-off dynamic storage with `ReadWriteMany` support.

**Comment by KF5JWC** [comment]
Another use case:

I ran into this lack of block volume support when trying to use `rook/rook` to work around the linode volume attachment limitations.

> `rpc error: code = Unimplemented desc = Block volume support is not yet implemented`

I am running many small (in data) applications. This runs into the 8 attached volume limit very quickly, and the only option for attaching more volumes is to buy another linode.

If using rook/ceph means a degraded experience compared to using volumes directly, that is still more acceptable for me than the cost of buying more servers for attaching exactly 8 more 15:1 overprovisioned volumes.
